//! `init` ported from rvl-cli `internal/commands/init.go` (po-av01j.163):
//! initialize Revelara for a repository.
//!
//! What it does, in rvl-cli's order: require a git repo, write
//! `.revelara.yaml` (project name + detected components) in the EXACT byte
//! shape rvl-cli's yaml.v3 marshal produces (4-space-indented list items
//! under `components:`), seed `.revelara/memory/digest.compact`, optionally
//! install the plugin skills, check credentials, fire the onboarding
//! milestone, and print the summary.
//!
//! Steps 4 and 5 write the REVELARA MANAGED BLOCK into `AGENTS.md` and
//! `CLAUDE.md` (see [`crate::context_files`]). init OWNS those files during
//! onboarding: it prompts about them itself, which is why the plugin step it
//! delegates to must not write them a second time.
//!
//! Deliberate deviations from the Go source:
//! * The plugin step DELEGATES to the rvl skills machinery (the same
//!   engine as `plugin install`) via a caller-supplied closure instead of
//!   porting rvl-cli's `internal/plugin` installer.
//! * `--no-context-files` is accepted here as well as on `plugin
//!   install`/`update`; rvl-cli carries it on the plugin commands only.
//! * Interactive prompts are plain stdin lines (matching `login`), not huh
//!   TUI forms. Only non-interactive paths (`-y`, flags) are tested.
//! * `--force` overwrites an existing `.revelara.yaml` without prompting,
//!   which is what rvl-cli's help text promises ("Overwrite existing config
//!   and plugin without prompting") even though its code still prompted.

use crate::context_files::Action;
use rvl_data::BIN;
use std::collections::HashSet;
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

/// Flags for `init`, mirroring rvl-cli's
/// `--project/--skip-plugin/--force/-y`.
pub struct InitArgs {
    pub project: Option<String>,
    pub skip_plugin: bool,
    pub force: bool,
    pub yes: bool,
    /// Skip steps 4 and 5 (the AGENTS.md/CLAUDE.md managed blocks).
    pub no_context_files: bool,
}

/// One `components:` entry in `.revelara.yaml` (rvl-cli
/// `project.ProjectComponent`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Component {
    pub name: String,
    pub path: String,
}

/// The comment header rvl-cli's `project.WriteProjectConfig` prepends.
const CONFIG_HEADER: &str = "# Revelara project configuration\n\
     # Used by /rvl:scan and reliability-review skills for consistent service naming\n";

/// The `.revelara/memory/digest.compact` skeleton (po-ta8wj.1 in rvl-cli).
const DIGEST_SKELETON: &str = "# digest.compact v1 - auto-generated by rvl init\n\
     # Do not hand-edit. Human-readable history is in RISKS.md and ENTRYPOINT.md.\n";

/// `init`: the full rvl-cli flow. `install_plugin` runs the rvl skills
/// machinery and reports whether any harness ended up installed.
pub fn run(args: InitArgs, install_plugin: impl FnOnce() -> anyhow::Result<bool>) -> ExitCode {
    println!("Initializing Revelara...");
    println!();

    // Step 1: require a git repo.
    let Some(git_root) = detect_git_root(Path::new(".")) else {
        eprintln!("Error: not a git repository.");
        eprintln!(
            "Revelara reads your git repository to detect project structure and service names."
        );
        eprintln!("Navigate to a git repository or run 'git init' here first.");
        return ExitCode::FAILURE;
    };

    // Step 2: generate .revelara.yaml.
    let config_path = git_root.join(".revelara.yaml");
    let mut write_config = true;
    if config_path.exists() {
        if args.force {
            // Documented --force contract: overwrite without prompting.
        } else if args.yes {
            write_config = false;
            println!("Keeping existing .revelara.yaml (use interactive mode to overwrite)");
        } else {
            let existing = std::fs::read_to_string(&config_path).unwrap_or_default();
            println!("Existing .revelara.yaml found:");
            println!("{existing}");
            if !crate::confirm("Overwrite existing .revelara.yaml?") {
                write_config = false;
                println!("Keeping existing .revelara.yaml");
            }
        }
    }

    let (project, components) = if write_config {
        let (project, declared, candidates) = build_project_config(&git_root, args.project, args.yes);
        if let Err(e) = std::fs::write(
            &config_path,
            render_config_yaml(&project, &declared, &candidates),
        ) {
            eprintln!("Error writing .revelara.yaml: {e}");
            return ExitCode::FAILURE;
        }
        match (declared.len(), candidates.len()) {
            (0, 0) => println!("Created .revelara.yaml (project: {project}, no components)"),
            (d, 0) => println!("Created .revelara.yaml (project: {project}, {d} declared components)"),
            (0, c) => println!(
                "Created .revelara.yaml (project: {project}, {c} candidate components commented out - uncomment to declare)"
            ),
            (d, c) => println!(
                "Created .revelara.yaml (project: {project}, {d} declared components, {c} candidates commented out)"
            ),
        }
        (project, declared)
    } else {
        load_existing(&config_path)
    };

    // Seed .revelara/memory/digest.compact if absent (best-effort).
    let memory_dir = git_root.join(".revelara").join("memory");
    match std::fs::create_dir_all(&memory_dir) {
        Err(e) => eprintln!("Warning: could not create .revelara/memory/: {e}"),
        Ok(()) => {
            let digest = memory_dir.join("digest.compact");
            if !digest.exists() {
                if let Err(e) = std::fs::write(&digest, DIGEST_SKELETON) {
                    eprintln!("Warning: could not write digest.compact: {e}");
                }
            }
        }
    }
    println!();

    // Step 3: install skills (the plugin) unless skipped.
    let mut plugin_installed = false;
    if !args.skip_plugin {
        let do_install = args.yes
            || args.force
            || crate::confirm("Install the Revelara plugin skills for detected coding agents?");
        if do_install {
            match install_plugin() {
                Ok(installed) => plugin_installed = installed,
                Err(e) => eprintln!("Warning: could not install skills: {e}"),
            }
        }
        println!();
    }

    // Step 4: the AGENTS.md managed block. Written for every repo, plugin
    // or not: it is how a harness with no slash commands finds rvl at all.
    let agents_md_action = if args.no_context_files {
        None
    } else {
        ensure_agents_md_interactive(&git_root, args.force, args.yes)
    };

    // Step 5: the CLAUDE.md managed block, only once skills are installed
    // (rvl-cli gates this on `pluginInstalled` — with no agent on the
    // machine there is nothing to give the extra Claude-only routing to).
    let claude_md_action = if args.no_context_files || !plugin_installed {
        None
    } else {
        report_context_action(
            "CLAUDE.md",
            crate::context_files::ensure_claude_md(&git_root, args.yes || args.force),
        )
    };
    if agents_md_action.is_some() || claude_md_action.is_some() {
        println!();
    }

    // Step 6: check credentials; on success record the onboarding
    // milestone (fire-and-forget, mirroring rvl-cli's "cli_setup").
    let mut credentials_configured = false;
    if let Ok(Some(cfg)) = rvl_data::config::load() {
        credentials_configured = true;
        println!("Credentials: Configured (API URL: {})", cfg.api_url);
        post_onboarding_milestone(&cfg);
    } else {
        println!("Credentials: Not configured");
        println!("  Run '{BIN} login' to set up API credentials.");
    }
    println!();

    // Step 7: summary.
    print_summary(
        &project,
        &components,
        plugin_installed,
        credentials_configured,
        agents_md_action,
        claude_md_action,
    );
    ExitCode::SUCCESS
}

/// rvl-cli `commands.EnsureAgentsMd`: prompt before touching an EXISTING
/// AGENTS.md (creating a fresh one was never prompted for), then delegate the
/// write so init and `plugin install` share one implementation.
fn ensure_agents_md_interactive(git_root: &Path, force: bool, yes: bool) -> Option<Action> {
    use crate::context_files::State;
    let mut proceed = force || yes;
    if !proceed {
        let title = match crate::context_files::agents_md_state(git_root) {
            State::Missing => {
                proceed = true;
                None
            }
            State::Unmanaged => Some("AGENTS.md exists but has no Revelara section. Append?"),
            State::Managed => Some("AGENTS.md already has Revelara section. Update?"),
        };
        if let Some(title) = title {
            if !crate::confirm(title) {
                println!("AGENTS.md: Skipped");
                return None;
            }
            proceed = true;
        }
    }
    if !proceed {
        println!("AGENTS.md: Skipped");
        return None;
    }
    report_context_action(
        "AGENTS.md",
        crate::context_files::ensure_agents_md(git_root, true),
    )
}

/// Print rvl-cli's per-action line and return the action when it wrote
/// something. A failure is a WARNING: init has already produced the config
/// the user asked for, and a context file is not worth failing over.
fn report_context_action(name: &str, res: anyhow::Result<Action>) -> Option<Action> {
    match res {
        Err(e) => {
            eprintln!("Warning: could not set up {name}: {e}");
            None
        }
        Ok(Action::Skipped) => {
            println!("{name}: Skipped");
            None
        }
        Ok(action) => {
            let verb = match action {
                Action::Created => "Created",
                Action::Appended => "Appended Revelara managed block to",
                Action::Updated => "Updated Revelara managed block in",
                Action::Skipped => unreachable!(),
            };
            match action {
                Action::Created => println!("Created {name} with Revelara managed block"),
                _ => println!("{verb} {name}"),
            }
            Some(action)
        }
    }
}

/// Fire-and-forget onboarding milestone. Errors are silently discarded so
/// init is never blocked or failed on behalf of a telemetry-style call
/// (rvl-cli `api.PostOnboardingMilestone`).
fn post_onboarding_milestone(cfg: &rvl_data::config::DataConfig) {
    if cfg.api_key.is_empty() || cfg.api_url.is_empty() {
        return;
    }
    let client = rvl_data::client::Client {
        api_url: cfg.api_url.clone(),
        api_key: cfg.api_key.clone(),
        org_id: None,
    };
    let url = format!("{}/api/v1/onboarding/milestone", cfg.api_url);
    let _ = client.request_with_timeout(
        "POST",
        &url,
        Some(br#"{"milestone":"cli_setup"}"#),
        std::time::Duration::from_secs(5),
    );
}

/// Port of rvl-cli's `printInitSummary`, minus the skills version (the
/// install machinery prints per-harness versions as it runs).
fn print_summary(
    project: &str,
    components: &[Component],
    plugin_installed: bool,
    credentials_configured: bool,
    agents_md_action: Option<Action>,
    claude_md_action: Option<Action>,
) {
    println!("=== Revelara Initialization Complete ===");
    println!();
    println!("Project: {project}");
    println!("Components: {}", components.len());
    for c in components {
        println!("  - {} ({})", c.name, c.path);
    }
    println!();
    if plugin_installed {
        println!("Skills: Installed");
    } else {
        println!("Skills: Not installed");
    }
    if let Some(a) = agents_md_action {
        println!("AGENTS.md: {}", a.as_str());
    }
    if let Some(a) = claude_md_action {
        println!("CLAUDE.md: {}", a.as_str());
    }
    if credentials_configured {
        println!("Credentials: Configured");
    } else {
        println!("Credentials: Not configured - run '{BIN} login'");
    }
    println!();
    println!("Next steps:");
    if !credentials_configured {
        println!("  1. {BIN} login");
        println!("  2. {BIN} plugin install claude");
    } else if !plugin_installed {
        println!("  1. {BIN} plugin install claude");
    }
    match (agents_md_action.is_some(), claude_md_action.is_some()) {
        (true, true) => {
            println!("  - Commit .revelara.yaml, AGENTS.md, and CLAUDE.md to your repository")
        }
        (true, false) => println!("  - Commit .revelara.yaml and AGENTS.md to your repository"),
        _ => println!("  - Commit .revelara.yaml to your repository"),
    }
    println!(
        "  - Open Claude Code in this directory and run /rvl:scan to scan for reliability risks"
    );
}

// --- config building ---

/// rvl-cli `buildProjectConfig`: auto-detect, then either accept defaults
/// (`-y`) or prompt.
fn build_project_config(
    git_root: &Path,
    project_flag: Option<String>,
    yes: bool,
) -> (String, Vec<Component>, Vec<Component>) {
    let mut name = match project_flag {
        Some(p) if !p.is_empty() => p,
        _ => detect_project_name(git_root),
    };
    let components = detect_components(git_root);

    if yes {
        // po-7p45k.19/.23: unattended runs declare NOTHING - detections
        // are written as commented candidates. No root-component fallback:
        // the project itself is the service.
        return (name, Vec::new(), components);
    }

    let input = prompt(&format!("Project name [{name}]: "));
    if !input.is_empty() {
        name = input;
    }

    if components.is_empty() {
        println!("No components auto-detected.");
        println!();
        println!("A component is a separately deployable service living in this repository (e.g., api/, worker/).");
        println!(
            "For a single-service repository, choose 'No' to treat the whole repo as one service."
        );
        println!();
        let declared = if crate::confirm("Add components manually?") {
            prompt_components()
        } else {
            Vec::new()
        };
        return (name, declared, Vec::new());
    }

    println!("Detected component candidates (separately runnable):");
    for (i, c) in components.iter().enumerate() {
        println!("  {}. {:<20} {}", i + 1, c.name, c.path);
    }
    println!();
    println!("Declaring a component makes it a service in the catalog under exactly");
    println!("that name, unique across your organization. Decline to keep them as");
    println!("commented candidates in .revelara.yaml instead.");
    println!();
    if crate::confirm("Declare these components as services?") {
        // po-7p45k.23: explicit acceptance IS the act of declaration.
        (name, components, Vec::new())
    } else {
        let declared = if crate::confirm("Add components manually instead?") {
            prompt_components()
        } else {
            Vec::new()
        };
        // Detections survive as commented candidates either way; drop any
        // name the user just declared manually.
        let candidates: Vec<Component> = components
            .into_iter()
            .filter(|c| !declared.iter().any(|d| d.name == c.name))
            .collect();
        (name, declared, candidates)
    }
}

/// rvl-cli `promptComponents`: collect name/path pairs until an empty entry.
fn prompt_components() -> Vec<Component> {
    println!("Enter a name and relative path for each component.");
    println!("Example: name=api, path=api/");
    println!();
    let mut components = Vec::new();
    loop {
        let name = prompt("Component name: ");
        let mut path = prompt("Component path (relative to repo root): ");
        if name.is_empty() || path.is_empty() {
            break;
        }
        if path != "." && !path.ends_with('/') {
            path.push('/');
        }
        println!("  Added: {name} -> {path}");
        components.push(Component { name, path });
        if !crate::confirm("Add another component?") {
            break;
        }
    }
    components
}

fn prompt(msg: &str) -> String {
    print!("{msg}");
    let _ = std::io::stdout().flush();
    let mut line = String::new();
    let _ = std::io::stdin().read_line(&mut line);
    line.trim().to_string()
}

/// Parse an existing `.revelara.yaml` just enough for the summary
/// (rvl-cli unmarshals into `ProjectConfig` the same way, ignoring errors).
fn load_existing(path: &Path) -> (String, Vec<Component>) {
    #[derive(serde::Deserialize, Default)]
    struct Cfg {
        #[serde(default)]
        project: String,
        #[serde(default)]
        components: Vec<CfgComponent>,
    }
    #[derive(serde::Deserialize)]
    struct CfgComponent {
        #[serde(default)]
        name: String,
        #[serde(default)]
        path: String,
    }
    let text = std::fs::read_to_string(path).unwrap_or_default();
    let cfg: Cfg = serde_yaml::from_str(&text).unwrap_or_default();
    (
        cfg.project,
        cfg.components
            .into_iter()
            .map(|c| Component {
                name: c.name,
                path: c.path,
            })
            .collect(),
    )
}

// --- YAML emission (byte parity with rvl-cli) ---

/// Render `.revelara.yaml` exactly as rvl-cli writes it: the comment header
/// plus Go yaml.v3's marshal shape — 4-space-indented `- name:` items with
/// `path:` aligned under `name:`. serde_yaml's emitter uses a different
/// indent style, so this is hand-rolled for byte parity.
fn render_config_yaml(project: &str, declared: &[Component], candidates: &[Component]) -> String {
    let mut out = String::from(CONFIG_HEADER);
    out.push_str(&format!("project: {}\n", yaml_scalar(project)));
    // po-7p45k.23: declared components (an explicit human act - interactive
    // acceptance or manual entry) render ACTIVE in the Go yaml.v3 marshal
    // shape. Unvetted detections render as commented candidates
    // (po-7p45k.19): each uncommented entry becomes a first-class
    // org-unique service, so unattended runs never declare silently.
    if declared.is_empty() && candidates.is_empty() {
        out.push_str("components: []\n");
    }
    if !declared.is_empty() {
        out.push_str("components:\n");
        for c in declared {
            out.push_str(&format!(
                "    - name: {}\n      path: {}\n",
                yaml_scalar(&c.name),
                yaml_scalar(&c.path)
            ));
        }
    }
    if !candidates.is_empty() {
        out.push_str(
            "# Detected component candidates. Uncommenting declares them: each\n\
             # entry becomes a service in the catalog under exactly that name,\n\
             # unique across your organization (name it like a dashboard\n\
             # service: payments-api, not api). See /help/services.\n",
        );
        if declared.is_empty() {
            out.push_str("# components:\n");
        }
        for c in candidates {
            out.push_str(&format!(
                "#     - name: {}\n#       path: {}\n",
                yaml_scalar(&c.name),
                yaml_scalar(&c.path)
            ));
        }
    }
    out
}

/// Quote a scalar only when it would not survive as a YAML plain scalar.
/// Project/component names and paths are almost always plain (yaml.v3
/// leaves them unquoted, including `.`).
fn yaml_scalar(v: &str) -> String {
    let plain = !v.is_empty()
        && v.chars()
            .all(|c| c.is_ascii_alphanumeric() || "._-/".contains(c))
        && !matches!(
            v.to_ascii_lowercase().as_str(),
            "true" | "false" | "null" | "~" | "yes" | "no" | "on" | "off"
        );
    if plain {
        v.to_string()
    } else {
        format!("\"{}\"", v.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

// --- detection (rvl-cli internal/project) ---

/// `git rev-parse --show-toplevel` from `dir`; `None` when not a git repo.
fn detect_git_root(dir: &Path) -> Option<PathBuf> {
    let out = std::process::Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let root = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if root.is_empty() {
        None
    } else {
        Some(PathBuf::from(root))
    }
}

/// Project name from the origin remote URL, falling back to the directory
/// name (rvl-cli `project.DetectProjectName`).
fn detect_project_name(git_root: &Path) -> String {
    if let Ok(out) = std::process::Command::new("git")
        .arg("-C")
        .arg(git_root)
        .args(["remote", "get-url", "origin"])
        .output()
    {
        if out.status.success() {
            let remote = String::from_utf8_lossy(&out.stdout).trim().to_string();
            let remote = remote
                .strip_suffix(".git")
                .map(str::to_string)
                .unwrap_or(remote);
            if let Some(seg) = remote.rsplit('/').next() {
                let name = seg.rsplit(':').next().unwrap_or(seg);
                if !name.is_empty() {
                    return name.to_string();
                }
            }
        }
    }
    git_root
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "project".to_string())
}

/// Directories never treated as components (rvl-cli `excludeDirs`).
const EXCLUDE_DIRS: &[&str] = &[
    "node_modules",
    "vendor",
    "venv",
    ".venv",
    "target",
    "build",
    "dist",
    ".git",
    "__pycache__",
    ".tox",
    "env",
];

/// Build files that mark a directory as a deployable component
/// (rvl-cli `buildFiles`).
const BUILD_FILES: &[&str] = &[
    "go.mod",
    "package.json",
    "Cargo.toml",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "pyproject.toml",
    "setup.py",
    "Gemfile",
    "mix.exs",
    "build.sbt",
    "CMakeLists.txt",
    "composer.json",
    "pubspec.yaml",
];

/// Dedup-by-path collector preserving insertion order, mirroring rvl-cli's
/// `addComponent` closure.
struct Collector {
    components: Vec<Component>,
    seen: HashSet<String>,
}

impl Collector {
    fn add(&mut self, name: impl Into<String>, path: impl Into<String>) {
        let path = path.into();
        if self.seen.insert(path.clone()) {
            self.components.push(Component {
                name: name.into(),
                path,
            });
        }
    }
}

fn base_name(path: &str) -> &str {
    path.trim_end_matches('/')
        .rsplit('/')
        .next()
        .unwrap_or(path)
}

fn excluded(name: &str) -> bool {
    EXCLUDE_DIRS.contains(&name)
}

/// Sorted directory entries (Go's `os.ReadDir` returns sorted entries;
/// Rust's `read_dir` does not, so sort for the same deterministic output).
fn sorted_dir(path: &Path) -> Vec<std::fs::DirEntry> {
    let mut entries: Vec<_> = match std::fs::read_dir(path) {
        Ok(rd) => rd.flatten().collect(),
        Err(_) => Vec::new(),
    };
    entries.sort_by_key(std::fs::DirEntry::file_name);
    entries
}

fn is_dir_entry(entry: &std::fs::DirEntry) -> bool {
    entry.file_type().map(|t| t.is_dir()).unwrap_or(false)
}

/// Multi-phase component detection, a faithful port of rvl-cli
/// `project.DetectComponents`: workspace declarations, build-file scanning
/// under common layout dirs, `cmd/*/main.go`, root Flutter apps, and
/// directories with Dockerfiles.
/// po-7p45k.23: a workspace member is a service CANDIDATE only when it is
/// separately runnable. A library crate/module is internal structure; its
/// findings belong to the project service, and proposing it would mint an
/// org-unique service for something that never deploys.
fn rust_member_has_binary(member: &Path) -> bool {
    if member.join("src/main.rs").exists() {
        return true;
    }
    if let Ok(entries) = std::fs::read_dir(member.join("src/bin")) {
        for e in entries.flatten() {
            if e.path().extension().is_some_and(|x| x == "rs") {
                return true;
            }
        }
    }
    std::fs::read_to_string(member.join("Cargo.toml"))
        .map(|t| t.contains("[[bin]]"))
        .unwrap_or(false)
}

/// Same gate for go.work members: `main.go` at the member root or a `cmd/`
/// tree marks a runnable module; anything else is a shared library.
fn go_member_has_binary(member: &Path) -> bool {
    member.join("main.go").exists() || member.join("cmd").is_dir()
}

pub(crate) fn detect_components(root: &Path) -> Vec<Component> {
    let mut col = Collector {
        components: Vec::new(),
        seen: HashSet::new(),
    };

    // Phase 1: workspace declarations.

    // Go workspaces (go.work).
    if let Ok(data) = std::fs::read_to_string(root.join("go.work")) {
        for line in data.lines() {
            let line = line.trim();
            if line.starts_with("use ") || (line.starts_with("./") && !line.starts_with("//")) {
                let dir = line.strip_prefix("use ").unwrap_or(line).trim();
                let dir = dir.trim_matches(|c| c == '.' || c == '/');
                if !dir.is_empty() && dir != "." && go_member_has_binary(&root.join(dir)) {
                    col.add(base_name(dir), format!("{dir}/"));
                }
            }
        }
    }

    // Rust workspaces (Cargo.toml [workspace] members). Same line-oriented
    // extraction as the Go source, including its quirk of skipping lines
    // that start with "members" (single-line member arrays go undetected).
    if let Ok(content) = std::fs::read_to_string(root.join("Cargo.toml")) {
        if content.contains("[workspace]") {
            for line in content.lines() {
                let line = line.trim();
                if line.contains('"') && !line.starts_with('#') && !line.starts_with("members") {
                    for part in line.split('"') {
                        let part = part.trim();
                        if !part.is_empty()
                            && !part.chars().any(|c| "[]=#,".contains(c))
                            && root.join(part).exists()
                            && rust_member_has_binary(&root.join(part))
                        {
                            col.add(base_name(part), format!("{part}/"));
                        }
                    }
                }
            }
        }
    }

    // JS/TS workspaces (package.json "workspaces").
    if let Ok(data) = std::fs::read_to_string(root.join("package.json")) {
        if let Ok(pkg) = serde_json::from_str::<serde_json::Value>(&data) {
            let mut patterns: Vec<String> = Vec::new();
            match pkg.get("workspaces") {
                Some(serde_json::Value::Array(arr)) => {
                    patterns.extend(arr.iter().filter_map(|v| v.as_str().map(String::from)));
                }
                Some(serde_json::Value::Object(obj)) => {
                    // Yarn v1 style: { "packages": ["..."] }.
                    if let Some(serde_json::Value::Array(arr)) = obj.get("packages") {
                        patterns.extend(arr.iter().filter_map(|v| v.as_str().map(String::from)));
                    }
                }
                _ => {}
            }
            for pattern in patterns {
                for m in glob_paths(root, &pattern) {
                    if m.is_dir() {
                        if let Ok(rel) = m.strip_prefix(root) {
                            let rel = rel.to_string_lossy().to_string();
                            if !rel.is_empty() && rel != "." {
                                col.add(base_name(&rel), format!("{rel}/"));
                            }
                        }
                    }
                }
            }
        }
    }

    // Java Maven modules (pom.xml <modules>).
    if let Ok(content) = std::fs::read_to_string(root.join("pom.xml")) {
        let mut rest = content.as_str();
        while let Some(start) = rest.find("<module>") {
            rest = &rest[start + 8..];
            let Some(end) = rest.find("</module>") else {
                break;
            };
            let module = rest[..end].trim().to_string();
            rest = &rest[end + 9..];
            if !module.is_empty() && root.join(&module).exists() {
                col.add(base_name(&module), format!("{module}/"));
            }
        }
    }

    // Gradle subprojects (settings.gradle / settings.gradle.kts).
    for settings in ["settings.gradle", "settings.gradle.kts"] {
        if let Ok(data) = std::fs::read_to_string(root.join(settings)) {
            for line in data.lines() {
                let line = line.trim();
                if line.contains("include") {
                    for part in line.split('\'') {
                        let part = part.trim();
                        let part = part.strip_prefix(':').unwrap_or(part);
                        if !part.is_empty() && !part.chars().any(|c| "()=,".contains(c)) {
                            let dir = part.replace(':', "/");
                            if root.join(&dir).exists() {
                                col.add(base_name(&dir).to_string(), format!("{dir}/"));
                            }
                        }
                    }
                }
            }
        }
    }

    // C# solution files (*.sln).
    for sln in glob_paths(root, "*.sln") {
        if let Ok(data) = std::fs::read_to_string(&sln) {
            for line in data.lines() {
                if line.contains("Project(") && line.contains(".csproj") {
                    for part in line.split('"') {
                        if part.ends_with(".csproj") || part.ends_with(".fsproj") {
                            let dir = match part.rfind('/') {
                                Some(i) => &part[..i],
                                None => ".",
                            };
                            if !dir.is_empty() && dir != "." {
                                let dir = dir.replace('\\', "/");
                                if root.join(&dir).exists() {
                                    col.add(base_name(&dir).to_string(), format!("{dir}/"));
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    // Dart/Flutter Melos workspaces (melos.yaml).
    if let Ok(data) = std::fs::read_to_string(root.join("melos.yaml")) {
        let mut in_packages = false;
        for line in data.lines() {
            let trimmed = line.trim();
            if trimmed == "packages:" {
                in_packages = true;
                continue;
            }
            if in_packages {
                if !trimmed.starts_with('-') && !trimmed.is_empty() {
                    break; // end of packages list
                }
                if let Some(pattern) = trimmed.strip_prefix("- ") {
                    for m in glob_paths(root, pattern.trim()) {
                        if m.is_dir() && m.join("pubspec.yaml").exists() {
                            if let Ok(rel) = m.strip_prefix(root) {
                                let rel = rel.to_string_lossy().to_string();
                                col.add(base_name(&rel).to_string(), format!("{rel}/"));
                            }
                        }
                    }
                }
            }
        }
    }

    // Phase 2: build files under common layout directories.
    for dir in [
        "services", "cmd", "apps", "packages", "libs", "modules", "internal",
    ] {
        for entry in sorted_dir(&root.join(dir)) {
            let name = entry.file_name().to_string_lossy().to_string();
            if !is_dir_entry(&entry) || excluded(&name) {
                continue;
            }
            let sub = format!("{dir}/{name}");
            if BUILD_FILES
                .iter()
                .any(|bf| root.join(&sub).join(bf).exists())
            {
                col.add(name, format!("{sub}/"));
            }
        }
    }

    // Phase 3: Go cmd/ pattern (directories with main.go).
    for entry in sorted_dir(&root.join("cmd")) {
        if !is_dir_entry(&entry) {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_string();
        if root.join("cmd").join(&name).join("main.go").exists() {
            col.add(name.clone(), format!("cmd/{name}/"));
        }
    }

    // Phase 3b: root Flutter/Dart app (pubspec.yaml + lib/).
    if root.join("pubspec.yaml").exists() && root.join("lib").exists() {
        if let Ok(data) = std::fs::read_to_string(root.join("pubspec.yaml")) {
            for line in data.lines() {
                if let Some(name) = line.trim().strip_prefix("name:") {
                    let name = name.trim();
                    if !name.is_empty() {
                        col.add(name.to_string(), ".");
                    }
                    break;
                }
            }
        }
    }

    // Phase 4: directories with Dockerfiles.
    for entry in sorted_dir(root) {
        let name = entry.file_name().to_string_lossy().to_string();
        if !is_dir_entry(&entry) || excluded(&name) {
            continue;
        }
        if root.join(&name).join("Dockerfile").exists() {
            col.add(name.clone(), format!("{name}/"));
        }
    }

    col.components
}

// --- minimal glob (Go filepath.Glob subset: `*` within a path segment) ---

/// Expand a glob pattern relative to `root`. Supports `*` within single
/// path segments (the shape of workspace globs like `packages/*`), which is
/// the subset rvl-cli's `filepath.Glob` calls rely on. Results are sorted.
fn glob_paths(root: &Path, pattern: &str) -> Vec<PathBuf> {
    let mut cur = vec![root.to_path_buf()];
    for seg in pattern.split('/').filter(|s| !s.is_empty()) {
        let mut next = Vec::new();
        if seg.contains('*') {
            for base in &cur {
                for entry in sorted_dir(base) {
                    let name = entry.file_name().to_string_lossy().to_string();
                    if seg_match(seg, &name) {
                        next.push(base.join(name));
                    }
                }
            }
        } else {
            for base in &cur {
                let p = base.join(seg);
                if p.exists() {
                    next.push(p);
                }
            }
        }
        cur = next;
    }
    cur.sort();
    cur
}

/// Match one glob segment (`*` = any run of characters) against a name.
fn seg_match(pattern: &str, name: &str) -> bool {
    let parts: Vec<&str> = pattern.split('*').collect();
    if parts.len() == 1 {
        return pattern == name;
    }
    let (first, last) = (parts[0], parts[parts.len() - 1]);
    if !name.starts_with(first) || !name.ends_with(last) {
        return false;
    }
    if name.len() < first.len() + last.len() {
        return false;
    }
    let mut rest = &name[first.len()..name.len() - last.len()];
    for part in &parts[1..parts.len() - 1] {
        if part.is_empty() {
            continue;
        }
        match rest.find(part) {
            Some(idx) => rest = &rest[idx + part.len()..],
            None => return false,
        }
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rust_workspace_library_members_are_not_candidates() {
        // po-7p45k.23: a workspace member without a binary target is an
        // internal library, not a service candidate. Only the member with
        // src/main.rs survives.
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        std::fs::write(
            root.join("Cargo.toml"),
            "[workspace]\nmembers = [\n    \"crates/app\",\n    \"crates/lib-a\",\n]\n",
        )
        .unwrap();
        for (m, bin) in [("crates/app", true), ("crates/lib-a", false)] {
            std::fs::create_dir_all(root.join(m).join("src")).unwrap();
            std::fs::write(root.join(m).join("Cargo.toml"), "[package]\n").unwrap();
            if bin {
                std::fs::write(root.join(m).join("src/main.rs"), "fn main() {}\n").unwrap();
            } else {
                std::fs::write(root.join(m).join("src/lib.rs"), "").unwrap();
            }
        }
        let got = detect_components(root);
        let names: Vec<&str> = got.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(names, vec!["app"], "{got:?}");
    }

    #[test]
    fn go_work_library_members_are_not_candidates() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        std::fs::write(root.join("go.work"), "use ./svc\nuse ./sharedlib\n").unwrap();
        std::fs::create_dir_all(root.join("svc")).unwrap();
        std::fs::write(root.join("svc/main.go"), "package main\n").unwrap();
        std::fs::create_dir_all(root.join("sharedlib")).unwrap();
        std::fs::write(root.join("sharedlib/util.go"), "package sharedlib\n").unwrap();
        let got = detect_components(root);
        let names: Vec<&str> = got.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(names, vec!["svc"], "{got:?}");
    }

    #[test]
    fn declared_components_render_active_candidates_commented() {
        // po-7p45k.23: interactive acceptance IS a declaration - declared
        // components render active (the Go yaml.v3 marshal shape),
        // candidates stay commented.
        let got = render_config_yaml(
            "myproj",
            &[Component {
                name: "api".into(),
                path: "api/".into(),
            }],
            &[Component {
                name: "maybe".into(),
                path: "maybe/".into(),
            }],
        );
        assert!(
            got.contains("components:\n    - name: api\n      path: api/\n"),
            "declared block wrong: {got}"
        );
        assert!(
            got.contains("#     - name: maybe\n#       path: maybe/\n"),
            "candidate block wrong: {got}"
        );
        let parsed: serde_yaml::Value = serde_yaml::from_str(&got).unwrap();
        assert_eq!(
            parsed["components"].as_sequence().map(|s| s.len()),
            Some(1),
            "only the declared component parses: {got}"
        );
    }

    #[test]
    fn init_candidates_commented() {
        // po-7p45k.19: detected components are CANDIDATES. They are
        // emitted commented out; uncommenting is the act of declaration.
        // No active `components:` key is written when candidates exist,
        // so a parse of the generated file yields zero declared
        // components.
        let got = render_config_yaml(
            "myproj",
            &[],
            &[Component {
                name: "api".into(),
                path: "api/".into(),
            }],
        );
        assert!(got.contains("# components:\n"), "candidates block missing: {got}");
        assert!(got.contains("#     - name: api\n"), "candidate entry missing: {got}");
        assert!(got.contains("#       path: api/\n"), "candidate path missing: {got}");
        // The only `components:` occurrence is the commented one.
        assert!(!got.contains("\ncomponents:"), "active components key must not be written: {got}");
        let parsed: serde_yaml::Value = serde_yaml::from_str(&got).expect("generated yaml parses");
        assert!(parsed.get("components").is_none(), "parse must see components as undeclared");
    }

    #[test]
    fn yaml_matches_rvl_cli_marshal_shape() {
        let got = render_config_yaml(
            "myproj",
            &[],
            &[
                Component {
                    name: "api".into(),
                    path: "api/".into(),
                },
                Component {
                    name: "worker".into(),
                    path: "worker/".into(),
                },
            ],
        );
        // Candidate entries keep the Go yaml.v3 marshal shape behind the
        // comment marker, so uncommenting yields exactly the byte shape
        // rvl-cli always wrote (verified against gopkg.in/yaml.v3 v3.0.1).
        assert!(got.contains("# components:\n#     - name: api\n#       path: api/\n#     - name: worker\n#       path: worker/\n"), "unexpected shape: {got}");
    }

    #[test]
    fn yaml_single_component_dot_path_stays_plain() {
        let got = render_config_yaml(
            "solo",
            &[],
            &[Component {
                name: "solo".into(),
                path: ".".into(),
            }],
        );
        assert!(got.contains("# components:\n#     - name: solo\n#       path: .\n"), "unexpected shape: {got}");
    }

    #[test]
    fn yaml_scalar_quotes_specials_only() {
        assert_eq!(yaml_scalar("api"), "api");
        assert_eq!(yaml_scalar("."), ".");
        assert_eq!(yaml_scalar("cmd/api/"), "cmd/api/");
        assert_eq!(yaml_scalar("a b"), "\"a b\"");
        assert_eq!(yaml_scalar("no"), "\"no\"");
    }

    #[test]
    fn seg_match_wildcards() {
        assert!(seg_match("*", "anything"));
        assert!(seg_match("*.sln", "app.sln"));
        assert!(!seg_match("*.sln", "app.slnx"));
        assert!(seg_match("pkg-*", "pkg-a"));
        assert!(!seg_match("a*a", "a"));
        assert!(seg_match("exact", "exact"));
        assert!(!seg_match("exact", "nope"));
    }

    #[test]
    fn detects_go_cmd_and_dockerfile_components() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        std::fs::create_dir_all(root.join("cmd/apiserver")).unwrap();
        std::fs::write(root.join("cmd/apiserver/main.go"), "package main\n").unwrap();
        std::fs::create_dir_all(root.join("worker")).unwrap();
        std::fs::write(root.join("worker/Dockerfile"), "FROM scratch\n").unwrap();

        let got = detect_components(root);
        assert!(got.contains(&Component {
            name: "apiserver".into(),
            path: "cmd/apiserver/".into()
        }));
        assert!(got.contains(&Component {
            name: "worker".into(),
            path: "worker/".into()
        }));
    }

    #[test]
    fn detects_go_work_and_package_json_workspaces() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        std::fs::write(
            root.join("go.work"),
            "go 1.22\n\nuse ./svc-a\nuse ./svc-b\n",
        )
        .unwrap();
        // po-7p45k.23: go.work members pass the gate only when runnable.
        std::fs::create_dir_all(root.join("svc-a")).unwrap();
        std::fs::write(root.join("svc-a/main.go"), "package main\n").unwrap();
        std::fs::create_dir_all(root.join("svc-b")).unwrap();
        std::fs::write(root.join("svc-b/lib.go"), "package svcb\n").unwrap();
        std::fs::create_dir_all(root.join("pkgs/web")).unwrap();
        std::fs::write(root.join("package.json"), r#"{"workspaces": ["pkgs/*"]}"#).unwrap();

        let got = detect_components(root);
        assert!(got.contains(&Component {
            name: "svc-a".into(),
            path: "svc-a/".into()
        }));
        assert!(
            !got.contains(&Component {
                name: "svc-b".into(),
                path: "svc-b/".into()
            }),
            "library go.work member must not be a candidate: {got:?}"
        );
        assert!(got.contains(&Component {
            name: "web".into(),
            path: "pkgs/web/".into()
        }));
    }
}
