[package]
name = "rvl-eval"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
rand = { workspace = true }
rvl-core = { path = "../rvl-core" }
rvl-spec = { path = "../rvl-spec" }
rvl-propagate = { path = "../rvl-propagate" }
