[package]
name = "rvlscan"
description = "Revelara reliability scanner"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
rvl-cache = { path = "../rvl-cache" }

[dev-dependencies]
tempfile = "3"
