//! Byte-parity JSON emission matching Go's `encoding/json`.
//!
//! rvl-cli is the output contract for the ported data commands, and its
//! `--format=json` paths fall into two regimes:
//!
//! 1. **Raw passthrough** — the Go CLI prints the server body verbatim
//!    (`fmt.Println(string(body))`). Nothing to do here; the caller prints
//!    the bytes + `\n`.
//! 2. **Re-marshal** — the Go CLI unmarshals, transforms, and re-marshals
//!    (`risk ready`, `risk context`, `knowledge procedures --control`).
//!    Matching those bytes requires Go's exact rules: struct-field order
//!    for typed values, sorted keys for maps, `MarshalIndent("", "  ")`
//!    layout, HTML escaping (`<` `>` `&` → `<` `>` `&`),
//!    and Go's float formatting (integral floats print without `.0`).
//!
//! The [`G`] tree models both regimes: `Obj` preserves the given field
//! order (a Go struct), `Dyn` re-emits arbitrary JSON the way Go re-emits
//! `map[string]any` (sorted keys, every number coerced to f64).
//! Goldens under `testdata/` are generated by Go itself
//! (`testdata/generate_goldens.go`) against the exact rvl-cli structs.

use serde_json::Value;

/// A JSON value with Go marshaling semantics attached.
pub enum G {
    Null,
    Bool(bool),
    /// Marshals like a Go `int`.
    Int(i64),
    /// Marshals like a Go `float64` (json floatEncoder rules).
    Float(f64),
    Str(String),
    Arr(Vec<G>),
    /// Field order is preserved — a Go struct.
    Obj(Vec<(String, G)>),
    /// Arbitrary JSON round-tripped through Go's `map[string]any` /
    /// `interface{}`: object keys sorted, every number a float64.
    Dyn(Value),
}

/// `json.MarshalIndent(v, "", "  ")` equivalent.
pub fn pretty(g: &G) -> String {
    let mut out = String::new();
    write_g(&mut out, g, 0, true);
    out
}

/// `json.Marshal(v)` equivalent (compact).
pub fn compact(g: &G) -> String {
    let mut out = String::new();
    write_g(&mut out, g, 0, false);
    out
}

fn write_indent(out: &mut String, depth: usize) {
    out.push('\n');
    for _ in 0..depth {
        out.push_str("  ");
    }
}

fn write_g(out: &mut String, g: &G, depth: usize, indent: bool) {
    match g {
        G::Null => out.push_str("null"),
        G::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
        G::Int(i) => out.push_str(&i.to_string()),
        G::Float(f) => out.push_str(&fmt_go_f64(*f)),
        G::Str(s) => write_go_string(out, s),
        G::Arr(items) => write_arr(out, items, depth, indent),
        G::Obj(fields) => write_obj(out, fields, depth, indent),
        G::Dyn(v) => write_dyn(out, v, depth, indent),
    }
}

fn write_arr(out: &mut String, items: &[G], depth: usize, indent: bool) {
    if items.is_empty() {
        out.push_str("[]");
        return;
    }
    out.push('[');
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        if indent {
            write_indent(out, depth + 1);
        }
        write_g(out, item, depth + 1, indent);
    }
    if indent {
        write_indent(out, depth);
    }
    out.push(']');
}

fn write_obj(out: &mut String, fields: &[(String, G)], depth: usize, indent: bool) {
    if fields.is_empty() {
        out.push_str("{}");
        return;
    }
    out.push('{');
    for (i, (k, v)) in fields.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        if indent {
            write_indent(out, depth + 1);
        }
        write_go_string(out, k);
        out.push(':');
        if indent {
            out.push(' ');
        }
        write_g(out, v, depth + 1, indent);
    }
    if indent {
        write_indent(out, depth);
    }
    out.push('}');
}

/// Arbitrary JSON, the way Go re-marshals `map[string]any`: object keys
/// sorted (serde_json's default map is a BTreeMap, already sorted) and
/// every number coerced through float64 — including the precision loss Go
/// incurs, which is exactly the parity we want.
fn write_dyn(out: &mut String, v: &Value, depth: usize, indent: bool) {
    match v {
        Value::Null => out.push_str("null"),
        Value::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
        Value::Number(n) => {
            let f = n.as_f64().unwrap_or(0.0);
            out.push_str(&fmt_go_f64(f));
        }
        Value::String(s) => write_go_string(out, s),
        Value::Array(items) => {
            if items.is_empty() {
                out.push_str("[]");
                return;
            }
            out.push('[');
            for (i, item) in items.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                if indent {
                    write_indent(out, depth + 1);
                }
                write_dyn(out, item, depth + 1, indent);
            }
            if indent {
                write_indent(out, depth);
            }
            out.push(']');
        }
        Value::Object(map) => {
            if map.is_empty() {
                out.push_str("{}");
                return;
            }
            out.push('{');
            for (i, (k, val)) in map.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                if indent {
                    write_indent(out, depth + 1);
                }
                write_go_string(out, k);
                out.push(':');
                if indent {
                    out.push(' ');
                }
                write_dyn(out, val, depth + 1, indent);
            }
            if indent {
                write_indent(out, depth);
            }
            out.push('}');
        }
    }
}

/// Go `encoding/json` string escaping with `SetEscapeHTML(true)` (the
/// default the CLI uses): `"` `\` escaped, `\n` `\r` `\t` shorthand, other
/// control bytes as `\u00xx` (lowercase hex), `<` `>` `&` as `<`
/// `>` `&`, and U+2028/U+2029 escaped.
fn write_go_string(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '<' => out.push_str("\\u003c"),
            '>' => out.push_str("\\u003e"),
            '&' => out.push_str("\\u0026"),
            '\u{2028}' => out.push_str("\\u2028"),
            '\u{2029}' => out.push_str("\\u2029"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
}

/// Go `encoding/json` float64 formatting: fixed notation (shortest
/// round-trip, integral values without a decimal point) for
/// `1e-6 <= |f| < 1e21`, otherwise `e` notation with Go's exponent
/// cleanup (`e-07` → `e-7`; positive exponents keep no padding since the
/// branch only triggers at `e+21` and beyond).
pub fn fmt_go_f64(f: f64) -> String {
    let abs = f.abs();
    if abs != 0.0 && !(1e-6..1e21).contains(&abs) {
        let s = format!("{f:e}"); // e.g. "1e21", "2.5e-7"
        let (mantissa, exp) = s.split_once('e').expect("{:e} always has an exponent");
        let exp: i32 = exp.parse().expect("exponent is an integer");
        if exp >= 0 {
            format!("{mantissa}e+{exp}")
        } else {
            format!("{mantissa}e-{}", -exp)
        }
    } else {
        // Rust's Display is shortest round-trip fixed notation and prints
        // integral floats without ".0" — same as strconv 'f' with -1.
        format!("{f}")
    }
}

/// Go `url.Values.Encode()` parity: keys sorted, `QueryEscape` applied to
/// keys and values (space → `+`, unreserved `A-Za-z0-9-_.~` kept, all
/// other bytes `%XX` uppercase hex).
pub fn query_encode(pairs: &[(&str, String)]) -> String {
    let mut sorted: Vec<&(&str, String)> = pairs.iter().collect();
    sorted.sort_by_key(|(k, _)| *k);
    let mut out = String::new();
    for (i, (k, v)) in sorted.iter().enumerate() {
        if i > 0 {
            out.push('&');
        }
        out.push_str(&query_escape(k));
        out.push('=');
        out.push_str(&query_escape(v));
    }
    out
}

/// Go `url.QueryEscape` parity.
pub fn query_escape(s: &str) -> String {
    let mut out = String::new();
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(b as char)
            }
            b' ' => out.push('+'),
            _ => out.push_str(&format!("%{b:02X}")),
        }
    }
    out
}

/// Go `url.PathEscape` parity: RFC 3986 path segment escaping. Unreserved
/// characters plus the sub-delims and `:@` survive; everything else is
/// `%XX`. Used for `/risks/{code}`-style path parameters.
pub fn path_escape(s: &str) -> String {
    let mut out = String::new();
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(b as char)
            }
            b'$' | b'&' | b'+' | b',' | b';' | b'=' | b':' | b'@' | b'!' | b'\'' | b'(' | b')'
            | b'*' => out.push(b as char),
            _ => out.push_str(&format!("%{b:02X}")),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn testdata(name: &str) -> String {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("testdata")
            .join(name);
        std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("reading {}: {e}", p.display()))
    }

    #[test]
    fn query_encode_matches_go_url_values() {
        // Golden generated by net/url's url.Values.Encode (see
        // testdata/generate_goldens.go).
        let golden = testdata("query_encode_golden.txt");
        let cases: Vec<Vec<(&str, String)>> = vec![
            vec![
                ("limit", "1000".into()),
                ("status", "applicable".into()),
                ("service", "a&b=c %".into()),
                ("category", "fault_tolerance".into()),
            ],
            vec![
                ("limit", "1000".into()),
                ("sort_by", "score".into()),
                ("sort_order", "desc".into()),
            ],
            vec![
                ("limit", "20".into()),
                ("vertical", "fault-tolerance".into()),
                ("technology", "go+redis".into()),
            ],
            vec![("limit", "200".into())],
            vec![
                ("q", "RC-018".into()),
                ("limit", "20".into()),
                ("type", "runbook".into()),
            ],
            vec![("query", "café ~tilde-_.x".into())],
        ];
        let got: String = cases
            .iter()
            .map(|c| query_encode(c) + "\n")
            .collect::<Vec<_>>()
            .join("");
        assert_eq!(got, golden);
    }

    #[test]
    fn compact_map_matches_go_marshal() {
        // knowledge search POST body: map[string]interface{} with sorted
        // keys, ints as ints, HTML-escaped strings.
        let golden = testdata("search_body_golden.txt");
        let g = G::Obj(vec![
            ("limit".into(), G::Int(20)),
            ("offset".into(), G::Int(0)),
            (
                "query".into(),
                G::Str("circuit breaker & <timeouts>".into()),
            ),
        ]);
        assert_eq!(compact(&g), golden);
    }

    #[test]
    fn dyn_pretty_sorts_keys_and_coerces_floats() {
        let v: Value =
            serde_json::from_str(r#"{"b":25.0,"a":"x & y","c":[1.5,{"z":1,"y":2}]}"#).unwrap();
        let got = pretty(&G::Dyn(v));
        // 25.0 -> "25" (Go float64), keys sorted at every level, & escaped.
        let want = "{\n  \"a\": \"x \\u0026 y\",\n  \"b\": 25,\n  \"c\": [\n    1.5,\n    {\n      \"y\": 2,\n      \"z\": 1\n    }\n  ]\n}";
        assert_eq!(got, want);
    }

    #[test]
    fn go_float_formatting_edges() {
        assert_eq!(fmt_go_f64(25.0), "25");
        assert_eq!(fmt_go_f64(0.9), "0.9");
        assert_eq!(fmt_go_f64(1.25), "1.25");
        assert_eq!(fmt_go_f64(0.0), "0");
        assert_eq!(fmt_go_f64(-0.5), "-0.5");
        assert_eq!(fmt_go_f64(1e21), "1e+21");
        assert_eq!(fmt_go_f64(2.5e-7), "2.5e-7");
        assert_eq!(fmt_go_f64(1.5e-10), "1.5e-10");
        assert_eq!(fmt_go_f64(1e-6), "0.000001");
    }

    #[test]
    fn string_escaping_matches_go() {
        let mut out = String::new();
        write_go_string(&mut out, "a<b>&\"\\\n\t\u{1}é");
        assert_eq!(out, "\"a\\u003cb\\u003e\\u0026\\\"\\\\\\n\\t\\u0001é\"");
    }

    #[test]
    fn empty_containers() {
        assert_eq!(pretty(&G::Arr(vec![])), "[]");
        assert_eq!(pretty(&G::Obj(vec![])), "{}");
        assert_eq!(compact(&G::Null), "null");
    }

    #[test]
    fn path_escape_keeps_risk_codes_verbatim() {
        assert_eq!(path_escape("R-001"), "R-001");
        assert_eq!(path_escape("a b/c%"), "a%20b%2Fc%25");
    }
}
