//! Ported rvl-cli data commands (po-av01j.17).
//!
//! rvl-cli (Go) is the contract source of truth: same subcommands, same
//! flags, byte-identical JSON output on the `--format=json` paths.
//! Human-readable output may improve. Each ported slice carries a
//! golden-parity suite; goldens under `testdata/` are generated by Go
//! itself against the exact rvl-cli structs (`testdata/generate_goldens.go`).
//!
//! Exit-code contract (mirrors rvl-cli's `cliutil`):
//!   0  success (including help)
//!   1  runtime failure (API error, auth failure, network problem)
//!   2  usage error (unknown flag, invalid argument) — clap parse errors
//!      already exit 2; validation failures use [`Failure::usage`].
//!
//! The binary is named `rvl` (renamed from `rvlscan` at the v1.0.0 cutover,
//! po-av01j.154); every user-facing hint routes through [`BIN`] (defined in
//! `rvl-core`, re-exported here), which is why the rename was one constant.

pub mod auth;
pub mod client;
pub mod config;
pub mod control;
pub mod display;
pub mod evidence;
pub mod feedback;
pub mod gojson;
pub mod incident;
pub mod knowledge;
pub mod project_config;
pub mod project_mapping;
pub mod risk;
pub mod scan_cached_output;
pub mod scan_normalize;
pub mod scan_submit;
pub mod scan_team;
pub mod stpa;

use std::process::ExitCode;

/// The binary name used in user-facing hints ("run 'rvl login'"), re-exported
/// from [`rvl_core`] so the ~57 `rvl_data::BIN` call sites keep working while
/// crates that do not depend on rvl-data can reach the same constant.
pub use rvl_core::BIN;

/// A command failure: the exact stderr message plus the process exit code.
#[derive(Debug, PartialEq, Eq)]
pub struct Failure {
    pub msg: String,
    pub code: u8,
}

impl Failure {
    /// Runtime failure (exit 1): API error, auth failure, network problem.
    pub fn runtime(msg: impl Into<String>) -> Self {
        Failure {
            msg: msg.into(),
            code: 1,
        }
    }
    /// Usage error (exit 2): invalid argument or flag value.
    pub fn usage(msg: impl Into<String>) -> Self {
        Failure {
            msg: msg.into(),
            code: 2,
        }
    }
}

/// stdout on success, (stderr, exit code) on failure.
pub type CmdResult = Result<String, Failure>;

/// Print a command result the way rvl-cli does: stdout verbatim on
/// success, the failure message to stderr + its exit code otherwise.
pub fn finish(res: CmdResult) -> ExitCode {
    match res {
        Ok(out) => {
            print!("{out}");
            ExitCode::SUCCESS
        }
        Err(f) => {
            eprintln!("{}", f.msg);
            ExitCode::from(f.code)
        }
    }
}
